### PR TITLE
Ja purchase seed stock

### PR DESCRIPTION
**Pull request by jessicaayerst**
You can now purchase seeds. However, you must create some plowed fields or natural fields or both in order to purchase the seeds and pick a field for them to go in.

### CODE REVIEW

**Comment by AFranklin41** [comment]
I tested by creating several plowed fields and natural fields and then purchasing seeds. 

Purchasing seeds seems to bring up the field selection options as it should (Sunflower can choose between both, Wildflower can only choose Natural, and Sesame can only choose Plowed), however when running the farm report the seeds do not appear to save to the individual fields.

**Comment by calebooski13** [comment]
When you create a facility and go to purchase seeds, 
1. Sunflower
2. Wildflower
3. Sesame
after you choose the field to place the plants, when you go to farm status it does not show the plants added into them. 

Issue: plants not saving to facility

**Comment by jessicaayerst** [comment]
I fixed the issue. Everything should work. Once you create a plowed or natural field, you can purchase seeds to go in the fields. They are displaying on the farm status now.

**Comment by AFranklin41** [comment]
Seeds appear to be showing up on the correct fields now in the farm status report. 

👍

**Comment by calebooski13** [comment]
The issue with placing the seeds to a field has been resolved

**Pull request merged**
